delete from files_users;
delete from weather_data_variables;
delete from power_systems;
delete from event_tags;
delete from weather_data;
delete from stations;
delete from station_locations;
delete from risk_models;
delete from locations;
delete from raw_weather_data;
delete from files;
delete from projects;
ALTER SEQUENCE files_users_id_seq RESTART WITH 1;
UPDATE files_users  SET id=nextval('files_users_id_seq');
ALTER SEQUENCE weather_data_variables_id_seq RESTART WITH 1;
UPDATE weather_data_variables  SET id=nextval('weather_data_variables_id_seq');
ALTER SEQUENCE power_systems_id_seq RESTART WITH 1;
UPDATE power_systems SET id=nextval('power_systems_id_seq');
ALTER SEQUENCE stations_id_seq RESTART WITH 1;
UPDATE stations SET id=nextval('stations_id_seq');
ALTER SEQUENCE station_locations_id_seq RESTART WITH 1;
UPDATE station_locations SET id=nextval('station_locations_id_seq');
ALTER SEQUENCE event_tags_id_seq RESTART WITH 1;
UPDATE event_tags SET id=nextval('event_tags_id_seq');
ALTER SEQUENCE risk_models_id_seq RESTART WITH 1;
UPDATE risk_models SET id=nextval('risk_models_id_seq');
ALTER SEQUENCE weather_data_id_seq RESTART WITH 1;
UPDATE weather_data SET id=nextval('weather_data_id_seq');
ALTER SEQUENCE locations_id_seq RESTART WITH 1;
UPDATE locations  SET id=nextval('locations_id_seq');
ALTER SEQUENCE raw_weather_data_id_seq RESTART WITH 1;
UPDATE raw_weather_data SET id=nextval('raw_weather_data_id_seq');
ALTER SEQUENCE files_id_seq RESTART WITH 1;
UPDATE files  SET id=nextval('files_id_seq');
